/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeneralFeedbackRouteImport } from './routes/api.general-feedback'
import { Route as ApiFeedbackRouteImport } from './routes/api.feedback'
import { Route as ApiCronScrapeRouteImport } from './routes/api.cron-scrape'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiAdminStatsRouteImport } from './routes/api.admin-stats'
import { Route as ApiAdminLogoutRouteImport } from './routes/api.admin-logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin-login'

const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneralFeedbackRoute = ApiGeneralFeedbackRouteImport.update({
  id: '/api/general-feedback',
  path: '/api/general-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronScrapeRoute = ApiCronScrapeRouteImport.update({
  id: '/api/cron-scrape',
  path: '/api/cron-scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin-stats',
  path: '/api/admin-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin-logout',
  path: '/api/admin-logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin-login',
  path: '/api/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/widget': typeof WidgetRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-logout': typeof ApiAdminLogoutRoute
  '/api/admin-stats': typeof ApiAdminStatsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cron-scrape': typeof ApiCronScrapeRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/general-feedback': typeof ApiGeneralFeedbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/widget': typeof WidgetRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-logout': typeof ApiAdminLogoutRoute
  '/api/admin-stats': typeof ApiAdminStatsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cron-scrape': typeof ApiCronScrapeRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/general-feedback': typeof ApiGeneralFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/widget': typeof WidgetRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/admin-logout': typeof ApiAdminLogoutRoute
  '/api/admin-stats': typeof ApiAdminStatsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/cron-scrape': typeof ApiCronScrapeRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/general-feedback': typeof ApiGeneralFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/widget'
    | '/api/admin-login'
    | '/api/admin-logout'
    | '/api/admin-stats'
    | '/api/chat'
    | '/api/cron-scrape'
    | '/api/feedback'
    | '/api/general-feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/widget'
    | '/api/admin-login'
    | '/api/admin-logout'
    | '/api/admin-stats'
    | '/api/chat'
    | '/api/cron-scrape'
    | '/api/feedback'
    | '/api/general-feedback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/widget'
    | '/api/admin-login'
    | '/api/admin-logout'
    | '/api/admin-stats'
    | '/api/chat'
    | '/api/cron-scrape'
    | '/api/feedback'
    | '/api/general-feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  WidgetRoute: typeof WidgetRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCronScrapeRoute: typeof ApiCronScrapeRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiGeneralFeedbackRoute: typeof ApiGeneralFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/general-feedback': {
      id: '/api/general-feedback'
      path: '/api/general-feedback'
      fullPath: '/api/general-feedback'
      preLoaderRoute: typeof ApiGeneralFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron-scrape': {
      id: '/api/cron-scrape'
      path: '/api/cron-scrape'
      fullPath: '/api/cron-scrape'
      preLoaderRoute: typeof ApiCronScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-stats': {
      id: '/api/admin-stats'
      path: '/api/admin-stats'
      fullPath: '/api/admin-stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-logout': {
      id: '/api/admin-logout'
      path: '/api/admin-logout'
      fullPath: '/api/admin-logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-login': {
      id: '/api/admin-login'
      path: '/api/admin-login'
      fullPath: '/api/admin-login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  WidgetRoute: WidgetRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCronScrapeRoute: ApiCronScrapeRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiGeneralFeedbackRoute: ApiGeneralFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
